### PR TITLE
fix: allow queue to clean up if not evict pods

### LINKED ISSUE #598: Graceful Termination of Karpenter is Hanging due to Eviction Queue
### Description

**Observed Behavior**:

Karpenter is now waiting for the full 30s timeout before fully terminating its pods. This is due to a hang that is initiated by the eviction queue due to a call to [`q.RateLimitingInterface.Get()`](https://github.com/aws/karpenter-core/blob/main/pkg/controllers/termination/terminator/eviction.go#L101) that will hang until another item enters the queue. This queue doesn't exit when context is canceled which causes Karpenter to hang terminating for the full 30s graceful termination period.

I was able to track this down during the graceful termination timeframe by getting callgraph from `/debug/pprof/goroutine?debug=1` and seeing these lines in there that indicate that the queue is still running and not exiting:

```bash
ob=
fl=
fn=(123)
+696916 0 0
cfl=
cfn=(124) github.com/aws/karpenter-core/pkg/operator/controller.(*Singleton).reconcile
calls=0 +697972 0
* * 1

ob=
fl=
fn=(124)
+1056 0 0
cfl=
cfn=(125) github.com/aws/karpenter-core/pkg/controllers/termination/terminator.(*Queue).Reconcile
calls=0 +3729504 0
* * 1
```

**Expected Behavior**:

Karpenter should gracefully terminate itself quickly (under 5s to finish all routines)

**Reproduction Steps** (Please include YAML):

1. Deploy Karpenter
2. Run `kubectl delete pods -n karpenter --all`
3. Note that Karpenter doesn't terminate itself quickly

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by njtran**
Fixes #598 

**Description**
Adds a check into the termination queue before calling `rateLimitingInterface.Get()` so that Karpenter can only call the rateLimitingInterface.Get() call if there's items in the queue. Calling Get() will wait until there's items in the queue, where it'll block Karpenter from shutting down until the shut down times out.

**How was this change tested?**
- make apply
- Ran `kubectl rollout restart deployment karpenter -n karpenter` a couple of times to see it not time out. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/termination/terminator/eviction.go [hunk 1]
```diff
@@ -97,9 +97,16 @@ func (q *Queue) Add(pods ...*v1.Pod) {
...
+	// Check if the queue is empty. client-go recommends not using this function to gate the subsequent
+	// get call, but since we're popping items off the queue synchronously, there should be no synchonization
+	// issues.
+	if q.Len() == 0 {
+		return reconcile.Result{RequeueAfter: 1 * time.Second}, nil
+	}
 	// Get pod from queue. This waits until queue is non-empty.
 	item, shutdown := q.RateLimitingInterface.Get()
 	if shutdown {
+		q.ShutDown()
```
Comment (jonathan-innis) [inline pkg/controllers/termination/terminator/eviction.go:109]: Why do we call shutdown here? Doesn't getting shutdown as a response from the Get() mean that it's already shutdown?

**Review by jonathan-innis — APPROVED** [review]
LGTM
