### PR TITLE
fix getDaemonSet to preserve pod affinity in daemonset template pod spec.

### LINKED ISSUE #532: Daemonsets that would not be provisioned on a provisioner are included in the scheduler calculation
### Description

**Observed Behavior**:
Daemonsets that would not be provisioned on a provisioner due to pod template affinity rules ( **not selector labels** ) are also included in the scheduler calculation in [getDaemonOverhead](https://github.com/aws/karpenter-core/blob/c6fb5c1c53220289fd77cdf07fb74f0250245c77/pkg/controllers/provisioning/scheduling/scheduler.go#L313) 

This issue occurs due to multiple reasons:

1. Daemonset pods are not generated from template but instead retrieved from cache of existing pods due to #3199 
2. Daemonset admission controller would replace the Pod nodeAffinity on creation to one that match to only 1 node:
> spec:
>   affinity:
>     nodeAffinity:
>       requiredDuringSchedulingIgnoredDuringExecution:
>         nodeSelectorTerms:
>         - matchFields:
>           - key: metadata.name
>             operator: In
>             values:
>             - ip-10-110-217-205.ap-southeast-1.compute.internal
3. Multiple daemonsets targeting different provisioners using node affinities and not selectors are running in the same namespace.

Thus, since no node selectors are defined, and all Pod affinity rules are rewritten by the admission controller, losing the information of nodeAffinity matchExpressions, all the daemonsets resources are considered in the overhead calculation process.

We can get around this with using proper Node Selectors, but we also wanted to utilise the NotIn operator for matchExpressions in nodeAffinity, and could not do the same with Node Selectors

**Expected Behavior**:
NodeAffinity defined in daemonset Pod templates should be respected even after admission controllers change them. 

**Reproduction Steps** (Please include YAML):
1. Create 1 provisioner(A) with instance types for 4cpu and labels `foo : bar`
2. Create another provisioner (B) with instance types for 2cpu and labels `foo: voo`
3. Create Daemonset(A) with requirements for 3cpu and select ProvisionerA using nodeAffinity rules within the Pod template:
> apiVersion: apps/v1
> kind: DaemonSet
> spec:
>   template:
>       spec:
>         affinity:
>           nodeAffinity:
>             requiredDuringSchedulingIgnoredDuringExecution:
>               nodeSelectorTerms:
>               - matchExpressions:
>                 - key: foo
>                   operator: In
>                   values:
>                   - bar
> 
4. Create Pod which targets provisioner B using nodeAffinity rules. 
5. Pod cannot be scheduled on provisioner B even though Daemonset A does not target provisioner B.

**Versions**:
- Chart Version: v0.30.0
- Kubernetes Version (`kubectl version`): 1.23

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by shikai93**
Fixes #532  

**Description**
Change getDaemonSetPods method to merge in daemon set template pod spec affinities with existing pod affinities to retain this information during scheduling. This would allow scheduler to not include daemonsets that would not be scheduled on a provisioner within their calculations of daemonset overhead

**How was this change tested?**
Unit tests included in the PR

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/provisioning/provisioner.go [hunk 1]
```diff
@@ -416,11 +416,144 @@ func (p *Provisioner) getDaemonSetPods(ctx context.Context) ([]*v1.Pod, error) {
 		pod := p.cluster.GetDaemonSetPod(&d)
 		if pod == nil {
 			pod = &v1.Pod{Spec: d.Spec.Template.Spec}
+		} else {
+			mergedAffinity := p.MergeAffinities(d.Spec.Template.Spec.Affinity, pod.Spec.Affinity)
```
Comment (jonathan-innis) [inline pkg/controllers/provisioning/provisioner.go:420]: Does it make sense to merge the affinities or just use the DaemonSet node affinity instead of the node affinity that comes from the pod, since that one will always get overridden by the DaemonSet controller as shown here: https://github.com/kubernetes/kubernetes/blob/c5cf0ac1889f55ab51749798bec684aed876709d/pkg/controller/daemon/util/daemonset_util.go#L176.

I think that could help simplify some things. You basically take every detail of the pod, except for the Required Node Affinities which you expect to be overridden by the DaemonSet controller.

Comment (shikai93) [reply pkg/controllers/provisioning/provisioner.go:420]: I was attempting to do a thorough merge in the event that kubernetes behaviour ever changes again in the future, but i do agree that it could simplify some stuff too, let me make the change

Comment (jonathan-innis) [reply pkg/controllers/provisioning/provisioner.go:420]: It seems unlikely to me that they will make a change there and (even if they did) we would just update our logic then when we see the logic changes in the new K8s version changelog

**Review by jonathan-innis — COMMENTED** [review]
Just one question

File: pkg/controllers/provisioning/provisioner.go [hunk 2]
```diff
@@ -416,6 +416,17 @@ func (p *Provisioner) getDaemonSetPods(ctx context.Context) ([]*v1.Pod, error) {
 		pod := p.cluster.GetDaemonSetPod(&d)
 		if pod == nil {
 			pod = &v1.Pod{Spec: d.Spec.Template.Spec}
+		} else if pod.Spec.Affinity != nil && pod.Spec.Affinity.NodeAffinity != nil &&
```
[the remark this answers is not in the document]
Comment (shikai93) [reply pkg/controllers/provisioning/provisioner.go]: agreed changed in the newer version 🙏

File: pkg/controllers/provisioning/provisioner_test.go [hunk 3]
```diff
@@ -537,6 +536,78 @@ var _ = Describe("Provisioning", func() {
 			Expect(*allocatable.Cpu()).To(Equal(resource.MustParse("4")))
 			Expect(*allocatable.Memory()).To(Equal(resource.MustParse("4Gi")))
 		})
+		It("should account for daemonset spec affinity ", func() {
+			ExpectCleanedUp(ctx, env.Client)
+			cluster.Reset()
```
Comment (jonathan-innis) [inline pkg/controllers/provisioning/provisioner_test.go:541]: This call and L540 get called during the AfterEach section for each Ginkgo test so we shouldn't need to execute them here.

File: pkg/controllers/provisioning/provisioner_test.go [hunk 4]
```diff
@@ -537,6 +536,78 @@ var _ = Describe("Provisioning", func() {
 			Expect(*allocatable.Cpu()).To(Equal(resource.MustParse("4")))
 			Expect(*allocatable.Memory()).To(Equal(resource.MustParse("4Gi")))
 		})
+		It("should account for daemonset spec affinity ", func() {
```
Comment (jonathan-innis) [inline pkg/controllers/provisioning/provisioner_test.go:539]:
```suggestion
		It("should account for daemonset spec affinity", func() {
```

**Review by jonathan-innis — COMMENTED** [review]
LGTM, just a couple things in the testing file

File: pkg/controllers/provisioning/provisioner_test.go (hunk 3 above)
Comment (shikai93) [reply pkg/controllers/provisioning/provisioner_test.go]: yes i forgot to clean them up as i was debugging the unit test setup. thanks for pointing out

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Review by tzneal — APPROVED** [review]
lgtm
