### PR TITLE
fix: Sync nodes that are Initialized from cluster state

### LINKED ISSUE #567: Provisioning can hang when `AWSNodeTemplate` doesn't exist and Karpenter is restart
### Description

**Observed Behavior**:

Karpenter continually gets "waiting on cluster sync" debug messages and will fail to launch new nodes until these messages are resolved.

```console
2023-10-02T22:18:41.625Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-127-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-127-151.us-west-2.compute.internal", "reconcileID": "7876abe2-f6cd-4fb8-aeaa-e283d9898be0", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.625Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-49.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-49.us-west-2.compute.internal", "reconcileID": "7a1155c1-f715-4d02-ae49-ff02f692ff4c", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.625Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-34-240.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-34-240.us-west-2.compute.internal", "reconcileID": "aea361a3-be1c-4c3b-925e-56e9f6e5d850", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.626Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-96-38.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-96-38.us-west-2.compute.internal", "reconcileID": "35c4e487-fa9c-4566-a243-abd92672955f", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.692Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-105-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-105-151.us-west-2.compute.internal", "reconcileID": "b584b268-7135-47ef-b64f-a9e028750404", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.710Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-65.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-65.us-west-2.compute.internal", "reconcileID": "1185cb38-21eb-44eb-8dce-04a750c0ad36", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.711Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-13-1.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-13-1.us-west-2.compute.internal", "reconcileID": "0d5bcc0a-e5ab-4bc8-bdc9-c1b3d29a66d4", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.711Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-138-12.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-138-12.us-west-2.compute.internal", "reconcileID": "4971514e-58e0-45c5-bd41-509725b26074", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.711Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-142-248.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-142-248.us-west-2.compute.internal", "reconcileID": "39840afd-ccd3-41ef-a4ae-a52c90997a77", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.711Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-117-82.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-117-82.us-west-2.compute.internal", "reconcileID": "fb9ae658-1736-4a26-ae3e-4cf82d1a9eaa", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.712Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-127-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-127-151.us-west-2.compute.internal", "reconcileID": "612b99fb-03e5-4b26-942e-114d6d71fb50", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.712Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-49.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-49.us-west-2.compute.internal", "reconcileID": "648584de-5012-4c2c-b471-3c1183ee4944", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.712Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-34-240.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-34-240.us-west-2.compute.internal", "reconcileID": "56124121-85a5-4edd-9b0d-888a7e36e11d", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.712Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-96-38.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-96-38.us-west-2.compute.internal", "reconcileID": "33bb90f4-b843-4f96-9c95-1cd1640f28fb", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.853Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-105-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-105-151.us-west-2.compute.internal", "reconcileID": "f1103767-d691-47b8-beb3-36087656bf36", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.872Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-65.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-65.us-west-2.compute.internal", "reconcileID": "396773a9-a69b-434f-9ce2-478cd858189e", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.872Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-13-1.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-13-1.us-west-2.compute.internal", "reconcileID": "d99b28b3-2e75-4fa7-8249-b6a02bb62f35", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.872Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-138-12.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-138-12.us-west-2.compute.internal", "reconcileID": "1b84eb9b-d42a-43dc-b0ef-77c3893255eb", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.873Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-142-248.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-142-248.us-west-2.compute.internal", "reconcileID": "d247e5f1-de2a-4cb9-8f3d-f3e8a44559d6", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.873Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-117-82.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-117-82.us-west-2.compute.internal", "reconcileID": "fd45bbf5-40b1-4447-87d0-2838e2aae6f9", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.873Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-127-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-127-151.us-west-2.compute.internal", "reconcileID": "f66ce51a-13b5-4cb1-b984-36dd48501547", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.874Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-49.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-49.us-west-2.compute.internal", "reconcileID": "60382751-755f-4ff2-95b3-36af5e55ac7b", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.874Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-34-240.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-34-240.us-west-2.compute.internal", "reconcileID": "22746a80-344c-45a0-bb6e-b180965276a2", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:41.874Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-96-38.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-96-38.us-west-2.compute.internal", "reconcileID": "e9ae3add-6e65-4a8b-90be-ec2712c04ded", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.174Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-105-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-105-151.us-west-2.compute.internal", "reconcileID": "54e8c768-d1ad-406b-bdcc-0c3c2dc8f346", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.186Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:42.193Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-65.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-65.us-west-2.compute.internal", "reconcileID": "95435c88-800a-4a7f-8f35-2ccf59b86604", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.193Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-13-1.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-13-1.us-west-2.compute.internal", "reconcileID": "97fde9c8-5b5b-43a5-961f-9cceef3d9794", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.193Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-138-12.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-138-12.us-west-2.compute.internal", "reconcileID": "9605ecec-8eb6-4043-80b4-e4d15b11e81f", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.194Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-142-248.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-142-248.us-west-2.compute.internal", "reconcileID": "fa469c4c-d7f4-4a77-a2af-6aedc3f0a560", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.194Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-117-82.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-117-82.us-west-2.compute.internal", "reconcileID": "11cebd7c-fd8e-42cf-aa50-9d39f3d8c7fb", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.194Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-127-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-127-151.us-west-2.compute.internal", "reconcileID": "019d050b-2d06-481f-bb95-8d6f485c9441", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.194Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-49.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-49.us-west-2.compute.internal", "reconcileID": "b4113152-ecc4-49f5-9010-5227c1ecee64", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.195Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-34-240.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-34-240.us-west-2.compute.internal", "reconcileID": "bc6fd6a4-b8bb-4436-aea7-2eb6dbb5bb56", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.195Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-96-38.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-96-38.us-west-2.compute.internal", "reconcileID": "c9845493-479c-4a0f-a0d2-61956f5961e7", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.814Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-105-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-105-151.us-west-2.compute.internal", "reconcileID": "505f66f4-33fe-41f6-b69d-f11320178a3d", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.834Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-65.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-65.us-west-2.compute.internal", "reconcileID": "9c12dad1-20fa-44d1-89be-8919a41108c5", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.834Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-13-1.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-13-1.us-west-2.compute.internal", "reconcileID": "bf3f49c8-749e-4cbb-9d0e-cf1e4ea317a8", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.834Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-138-12.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-138-12.us-west-2.compute.internal", "reconcileID": "abe061d2-f6f4-4d51-8420-0a50c41664f3", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.835Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-142-248.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-142-248.us-west-2.compute.internal", "reconcileID": "0f45af10-bf9c-4086-91d2-db5106f467fa", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.836Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-117-82.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-117-82.us-west-2.compute.internal", "reconcileID": "020eb229-ea80-4d34-8754-88244d904707", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.837Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-127-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-127-151.us-west-2.compute.internal", "reconcileID": "e1b39302-2457-4816-9d9f-e36466131bd2", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.838Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-49.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-49.us-west-2.compute.internal", "reconcileID": "1f5d2595-f05a-40ad-b6a4-4c52ce05373b", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.840Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-34-240.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-34-240.us-west-2.compute.internal", "reconcileID": "5663d96e-f7f7-4482-a335-c7e04c78065b", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:42.840Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-96-38.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-96-38.us-west-2.compute.internal", "reconcileID": "20d0ec7f-8d4a-4e91-b363-6f5cb7d457c9", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:43.187Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:43.941Z        DEBUG   controller.pricing      updated on-demand pricing       {"commit": "2f1a308", "instance-type-count": 727}
2023-10-02T22:18:44.095Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-105-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-105-151.us-west-2.compute.internal", "reconcileID": "eb16c6ec-8fa9-4bad-8be3-685e317600b7", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:44.115Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-65.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-65.us-west-2.compute.internal", "reconcileID": "bcfea82e-8474-4806-81c4-95cb1d80ff75", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:44.115Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-13-1.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-13-1.us-west-2.compute.internal", "reconcileID": "5cde6fe4-25c7-45d1-9040-aa8b89624c8b", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:44.115Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-138-12.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-138-12.us-west-2.compute.internal", "reconcileID": "b54e9a9a-1e40-4d0c-8fe3-cdb6cab01544", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:44.116Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-142-248.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-142-248.us-west-2.compute.internal", "reconcileID": "0b6b70d6-fcee-4f00-81c6-f2b1aa22a991", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:44.117Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-117-82.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-117-82.us-west-2.compute.internal", "reconcileID": "3980973b-de2b-43c1-a054-46bd56cdad0f", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:44.117Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-127-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-127-151.us-west-2.compute.internal", "reconcileID": "42acb211-e8d1-47fb-b1cb-d6523e47a513", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:44.119Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-49.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-49.us-west-2.compute.internal", "reconcileID": "ab8c59b2-4f56-4ae9-9e4f-5f8e751ef90c", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:44.121Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-34-240.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-34-240.us-west-2.compute.internal", "reconcileID": "603dabdb-726a-4cff-a65b-b74f72563467", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:44.121Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-96-38.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-96-38.us-west-2.compute.internal", "reconcileID": "b0311cca-f978-4452-a448-64c27d6f83c8", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:44.188Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:45.188Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:46.190Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:46.656Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-105-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-105-151.us-west-2.compute.internal", "reconcileID": "50965baf-aca8-4723-a2cc-b27756190dd4", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:46.675Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-65.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-65.us-west-2.compute.internal", "reconcileID": "80159f26-3ead-4ffd-a4a7-852dcc564094", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:46.676Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-13-1.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-13-1.us-west-2.compute.internal", "reconcileID": "9e2d2b1a-12fc-43a4-b2d0-9c05951e3865", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:46.676Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-138-12.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-138-12.us-west-2.compute.internal", "reconcileID": "eebf8849-f17f-458b-9913-103e60da838a", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:46.676Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-142-248.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-142-248.us-west-2.compute.internal", "reconcileID": "2d085e6d-26e5-4154-ab15-2e60fb841cb9", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:46.678Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-117-82.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-117-82.us-west-2.compute.internal", "reconcileID": "6304912e-971a-41ee-a095-d23e4445ec9c", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:46.678Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-127-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-127-151.us-west-2.compute.internal", "reconcileID": "96c6b28b-a93f-4129-8b82-c1d06f79f3ae", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:46.679Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-49.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-49.us-west-2.compute.internal", "reconcileID": "46352931-d63b-455c-98cf-116c1108d50b", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:46.682Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-34-240.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-34-240.us-west-2.compute.internal", "reconcileID": "7f7ba62b-368d-416b-8694-0142eda5caab", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:46.682Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-96-38.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-96-38.us-west-2.compute.internal", "reconcileID": "1cdefb47-71d1-444f-a56d-c5d83adf9178", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:47.191Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:48.192Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:49.193Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:50.194Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:51.194Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:51.777Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-105-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-105-151.us-west-2.compute.internal", "reconcileID": "c0e042e7-a881-4d08-9ea9-ba7f7cb26f31", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:51.796Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-65.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-65.us-west-2.compute.internal", "reconcileID": "7819a8a9-39ea-4e56-a7ea-bd55c62e2372", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:51.796Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-13-1.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-13-1.us-west-2.compute.internal", "reconcileID": "d1df7a3f-032b-4dfb-872f-5f28a92c6c02", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:51.796Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-138-12.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-138-12.us-west-2.compute.internal", "reconcileID": "15a13a39-e4ce-4d7d-9195-a404b7164431", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:51.797Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-142-248.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-142-248.us-west-2.compute.internal", "reconcileID": "2e5225d4-c23a-4178-b57b-5382908c6e8a", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:51.798Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-117-82.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-117-82.us-west-2.compute.internal", "reconcileID": "a9a6a398-a82a-45d1-baaa-b4338a030f89", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:51.798Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-127-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-127-151.us-west-2.compute.internal", "reconcileID": "5048cb20-b95d-4c8a-8cb5-dbab2b0b1c8c", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:51.799Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-49.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-49.us-west-2.compute.internal", "reconcileID": "c44616ce-5d67-4226-a803-7edf6aef53ce", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:51.802Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-34-240.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-34-240.us-west-2.compute.internal", "reconcileID": "1ed44a3d-a2b5-4d3c-a97f-23484326268a", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:51.802Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-96-38.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-96-38.us-west-2.compute.internal", "reconcileID": "919135a5-fea2-44a3-9ac1-eaae92287bd5", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:52.195Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:53.196Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:54.197Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:54.973Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-117-82.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-117-82.us-west-2.compute.internal", "reconcileID": "7cbc7f5c-edd2-4a5c-8279-88e7e482f315", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:55.197Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:55.788Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-26-65.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-26-65.us-west-2.compute.internal", "reconcileID": "2d521a9b-6d7f-4c63-af55-1d0959723567", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:56.198Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:57.199Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:57.946Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-142-248.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-142-248.us-west-2.compute.internal", "reconcileID": "ed66391c-2044-47d4-ab69-3a7eb19c8605", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:58.200Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:59.001Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-34-240.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-34-240.us-west-2.compute.internal", "reconcileID": "fc9de627-3669-43e1-b24d-ce84acd1a27e", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:59.201Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
2023-10-02T22:18:59.216Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-105-151.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-105-151.us-west-2.compute.internal", "reconcileID": "5b41ca50-d70d-4dd4-b9b5-98fe30bad19c", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:18:59.922Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-138-12.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-138-12.us-west-2.compute.internal", "reconcileID": "78878ee1-21ba-4a08-9894-30a01ebb2992", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:19:00.152Z        ERROR   controller      Reconciler error        {"commit": "2f1a308", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-96-38.us-west-2.compute.internal"}, "namespace": "", "name": "ip-192-168-96-38.us-west-2.compute.internal", "reconcileID": "d6bdb6d6-0e20-4a32-8b03-380c87b81edd", "error": "resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"default\" not found"}
2023-10-02T22:19:00.202Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "2f1a308"}
```

**Expected Behavior**:

Karpenter shouldn't expect that it has to look up the instance type allocatable when it is dealing with nodes that are fully up and already initialized. 

**Reproduction Steps** (Please include YAML):

1. Deploy Provisioner, AWSNodeTemplate, and Deployment
2. Let Karpenter scale up the Machines and Nodes
3. Delete the AWSNodeTemplate
4. Restart Karpenter

**Versions**:
- Chart Version: v0.31.0
- Kubernetes Version (`kubectl version`): 

```console
➜  karpenter (main) k version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4-eks-2d98532

```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by engedaam**
Fixes #567 

**Description**
- Provisioning can hang when AWSNodeTemplate doesn't exist and Karpenter is restart, this will block karpenter from provisioning and deprovisioning nodes 

**How was this change tested?**
- Manually tested

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/state/cluster.go [hunk 1]
```diff
@@ -513,6 +513,14 @@ func (c *Cluster) populateInflight(ctx context.Context, n *StateNode) error {
 	if err != nil {
 		return client.IgnoreNotFound(err)
 	}
+	if n.NodeClaim != nil && n.Node != nil {
```
Comment (jonathan-innis) [inline pkg/controllers/state/cluster.go:516]: I think we can just get away with a condition here that checks if the node is initialized and returns nil to exit if it is. Since the inflightAllocatable is _only_ used if the node isn't initialized, I think that should be sufficient. So something like

```go
if n.Initialized() {
  return nil
}
```

File: pkg/controllers/state/cluster.go [hunk 2]
```diff
@@ -513,6 +513,14 @@ func (c *Cluster) populateInflight(ctx context.Context, n *StateNode) error {
...
+		if initializedCond := n.NodeClaim.StatusConditions().GetCondition(v1beta1.Initialized); initializedCond.IsTrue() {
```
Comment (jonathan-innis) [inline pkg/controllers/state/cluster.go:517]: If we're adding this change, we definitely need a test in the `state/suite_test.go` file to validate this behavior. Can you add the test case?

File: pkg/controllers/state/cluster.go [hunk 3]
```diff
@@ -513,6 +513,12 @@ func (c *Cluster) populateInflight(ctx context.Context, n *StateNode) error {
 	if err != nil {
 		return client.IgnoreNotFound(err)
 	}
+	if n.Initialized() {
+		n.inflightInitialized = true
+		n.inflightCapacity = n.Node.Status.Capacity
```
Comment (jonathan-innis) [inline pkg/controllers/state/cluster.go:518]: Is there an `n.Capacity()` function?

File: pkg/controllers/state/suite_test.go [hunk 4]
```diff
@@ -523,6 +523,38 @@ var _ = Describe("Inflight Nodes", func() {
 		// Still expect to succeed w/o instance type since inflight details are set once
 		ExpectReconcileSucceeded(ctx, nodeController, client.ObjectKeyFromObject(node))
 	})
+	It("should populate node from the cluster if the node initialized", func() {
+		instanceType := cloudProvider.InstanceTypes[0]
+		fmt.Println(instanceType)
```
Comment (jonathan-innis) [inline pkg/controllers/state/suite_test.go:528]: nit: drop

File: pkg/controllers/state/suite_test.go [hunk 5]
```diff
@@ -523,6 +523,38 @@ var _ = Describe("Inflight Nodes", func() {
 		// Still expect to succeed w/o instance type since inflight details are set once
 		ExpectReconcileSucceeded(ctx, nodeController, client.ObjectKeyFromObject(node))
 	})
+	It("should populate node from the cluster if the node initialized", func() {
+		instanceType := cloudProvider.InstanceTypes[0]
```
Comment (jonathan-innis) [inline pkg/controllers/state/suite_test.go:527]: I think we want to enforce the scenario we know that can happen here, which is that the GetInstanceTypes() call returns no valid instance types, but we still want to succeed to propagate resources. There's an `InstanceTypes` part of the fake cloudprovider that you could use to assign no instance types to the `GetInstanceTypes()` call so that you ensure that this is properly tested.

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀
